services:
  - type: web
    name: moodybot-webapp
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - "server/**"
        - "client/**"
        - "package.json"
        - "package-lock.json" 